### ISSUE TITLE
Error LLVM Linux

### ISSUE THREAD

**Issue by latot** [DHrpcs3/rpcs3#1007]
Hi again, when i set the cpu setting to PPU JIT (LLVM) and i try to run a game the program crash, log:

https://gist.github.com/latot/56c259f58bee536cd6c0.

ans some times the log change to:

segmentation violation

**Comment by Syphurith** [comment]
Eh.. What happens if you set it to Interpreter instead?
LLVM branch is in **WIP state**. And if you insist to have a try of that, i suggust you to check out Neko's branch not DHrpcs3's (Well neko..). But if you face some problem in his branch, please not to disturb him too much (the repo on dev's pc should be newer than the one on github). Besides that is not recommended - you know that it is in WIP.
To some guys, "segmentation violation"="Segment Fault"="Access Violation". These happens when you tried to access memory that invalid to you. And for "pure virtual method called", see [here](http://stackoverflow.com/questions/10707286/how-to-resolve-pure-virtual-method-called) if you know C++ enough.
And always if you have some notes for them, you can go to irc and talk to them.
Just from the log i can not get where caused the problem, maybe you can try using gdb to know where it was triggered, or read those codes to find out where may cause problems. Help solving problems is a way to help developing.

**Comment by latot** [comment]
Oh, sorry, i read the info but i don't find about the llvm, i'll have more care with this, sorry .
